import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: '#fcf8ff',
        'surface-dim': '#dcd8e3',
        'surface-bright': '#fcf8ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f6f2fd',
        'surface-container': '#f0ecf7',
        'surface-container-high': '#ebe6f2',
        'surface-container-highest': '#e5e1ec',
        'on-surface': '#1c1b23',
        'on-surface-variant': '#474554',
        'inverse-surface': '#312f38',
        'inverse-on-surface': '#f3effa',
        outline: '#787585',
        'outline-variant': '#c8c4d6',
        'surface-tint': '#574acb',
        primary: '#4234b6',
        'on-primary': '#ffffff',
        'primary-container': '#5b4fcf',
        'on-primary-container': '#e0dbff',
        'inverse-primary': '#c5c0ff',
        secondary: '#5f52a8',
        'on-secondary': '#ffffff',
        'secondary-container': '#b0a2ff',
        'on-secondary-container': '#423389',
        tertiary: '#763b00',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#9a4e00',
        'on-tertiary-container': '#ffd7be',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#e4dfff',
        'primary-fixed-dim': '#c5c0ff',
        'on-primary-fixed': '#140067',
        'on-primary-fixed-variant': '#3e2fb2',
        'secondary-fixed': '#e5deff',
        'secondary-fixed-dim': '#c9bfff',
        'on-secondary-fixed': '#1b0063',
        'on-secondary-fixed-variant': '#47398f',
        'tertiary-fixed': '#ffdcc5',
        'tertiary-fixed-dim': '#ffb783',
        'on-tertiary-fixed': '#301400',
        'on-tertiary-fixed-variant': '#703700',
        background: '#fcf8ff',
        'on-background': '#1c1b23',
        'surface-variant': '#e5e1ec',
      },
      spacing: {
        'max-container': '1200px',
        'stack-gap': '16px',
        'edge-margin': '24px',
        'section-gap': '80px',
        gutter: '20px',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
      },
      boxShadow: {
        soft: '0px 4px 12px rgba(36, 16, 107, 0.04)',
        hover: '0px 8px 24px rgba(36, 16, 107, 0.08)',
      },
    },
  },
  plugins: [],
};
export default config;
