-- Supabase lead workflow storage.
-- Firebase remains the auth/account source; this table stores lead handling state.

create table if not exists public.leads (
  id text primary key,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create unique index if not exists leads_id_unique_idx on public.leads (id);

alter table public.leads
  add column if not exists mention_id text,
  add column if not exists source_mention_id text,
  add column if not exists parent_id text,
  add column if not exists content_type text,
  add column if not exists post_id text,
  add column if not exists workspace_id text,
  add column if not exists brand text,
  add column if not exists platform text,
  add column if not exists source text,
  add column if not exists author text,
  add column if not exists content text,
  add column if not exists text text,
  add column if not exists intent text,
  add column if not exists current_label text,
  add column if not exists labels jsonb,
  add column if not exists current_labels jsonb,
  add column if not exists intent_signals text[],
  add column if not exists status text default 'new',
  add column if not exists expiry_at timestamptz,
  add column if not exists posted_at timestamptz,
  add column if not exists url text,
  add column if not exists post_url text,
  add column if not exists source_url text,
  add column if not exists label_correction_status text,
  add column if not exists pending_label_request_id text,
  add column if not exists last_label_corrected_at timestamptz,
  add column if not exists phone text,
  add column if not exists email text,
  add column if not exists zalo_id text,
  add column if not exists messenger_id text,
  add column if not exists social_profile_url text,
  add column if not exists contact text,
  add column if not exists profile_url text,
  add column if not exists firebase_uid text,
  add column if not exists owner_id text,
  add column if not exists owner_name text,
  add column if not exists owner_email text,
  add column if not exists assigned_at timestamptz,
  add column if not exists assigned_by text,
  add column if not exists claimed_at timestamptz,
  add column if not exists first_contacted_at timestamptz,
  add column if not exists contact_attempts integer default 0,
  add column if not exists last_contact_at timestamptz,
  add column if not exists pending_result boolean default false,
  add column if not exists last_action_at timestamptz,
  add column if not exists last_action_type text,
  add column if not exists last_contact_channel text,
  add column if not exists result_type text,
  add column if not exists result_recorded_at timestamptz,
  add column if not exists follow_up_at timestamptz,
  add column if not exists closed_at timestamptz,
  add column if not exists sales_status text,
  add column if not exists sales_owner_id text,
  add column if not exists sales_owner_name text,
  add column if not exists sales_transferred_at timestamptz,
  add column if not exists crm_deal_id text,
  add column if not exists notes text,
  add column if not exists updated_by text,
  add column if not exists updated_by_role text;
