import type {
  Mention,
  Alert,
  Lead,
  Workspace,
  LabelChangeRequest,
} from "@/types/dashboard";

export const dummyWorkspaces: Workspace[] = [
  { 
    id: "Demo Brand", 
    brand_name: "Demo Brand", 
    scale: "large",
    keywords: ["demo"],
    synonyms: [],
    priority: true,
    created_at: new Date().toISOString()
  },
];

export const dummyMentions: Mention[] = [
  {
    id: "m1",
    labels: { sentiment: "positive", topic: ["service"], relevance: true, urgency: "none", intent: "none" },
    workspace_id: "Demo Brand",
    platform: "facebook",
    post_id: "p1",
    content: "Sản phẩm của Demo Brand dùng rất tốt, nhân viên tư vấn nhiệt tình. Sẽ ủng hộ dài dài!",
    content_type: "post",
    author: "Nguyễn Văn A",
    sentiment: "positive",
    topic: "service",
    credibility_score: 85,
    url: "https://facebook.com/123",
    posted_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "m2",
    labels: { sentiment: "negative", topic: ["quality"], relevance: true, urgency: "high", intent: "none" },
    workspace_id: "Demo Brand",
    platform: "tiktok",
    post_id: "p2",
    content: "Mọi người cẩn thận nhé, mình mua về dùng bị dị ứng nổi mẩn đỏ khắp người. Đã nhắn tin cho page nhưng không ai rep, thái độ cực kỳ vô trách nhiệm!!!",
    content_type: "post",
    author: "@trangnguyen_review",
    sentiment: "negative",
    topic: "quality",
    credibility_score: 98,
    url: "https://tiktok.com/123",
    posted_at: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
  },
  {
    id: "m3",
    labels: { sentiment: "negative", topic: ["service"], relevance: true, urgency: "high", intent: "none" },
    workspace_id: "Demo Brand",
    platform: "thread",
    post_id: "p3",
    content: "Tẩy chay Demo Brand ngay lập tức! Quảng cáo một đằng giao hàng một nẻo, lừa đảo khách hàng trắng trợn 🤬",
    content_type: "post",
    author: "Le Minh Kiet",
    sentiment: "negative",
    topic: "service",
    credibility_score: 92,
    url: "https://threads.net/123",
    posted_at: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
  },
  {
    id: "m4",
    labels: { sentiment: "negative", topic: ["service"], relevance: true, urgency: "high", intent: "none" },
    workspace_id: "Demo Brand",
    platform: "google_maps",
    post_id: "p4",
    content: "Nhân viên chi nhánh Quận 1 thái độ lồi lõm, mắng khách như tát nước vào mặt. Trải nghiệm quá tồi tệ, 1 sao!",
    content_type: "comment",
    author: "Trần Hữu Thắng",
    sentiment: "negative",
    topic: "staff",
    credibility_score: 75,
    url: "https://maps.google.com/123",
    posted_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "m5",
    labels: { sentiment: "neutral", topic: ["other"], relevance: true, urgency: "none", intent: "none" },
    workspace_id: "Demo Brand",
    platform: "news",
    post_id: "p5",
    content: "Thương hiệu Demo Brand vừa ra mắt bộ sưu tập mới thu hút sự chú ý lớn từ giới trẻ.",
    content_type: "post",
    author: "Báo Dân Trí",
    sentiment: "neutral",
    topic: "other",
    credibility_score: 99,
    url: "https://dantri.com.vn",
    posted_at: new Date(Date.now() - 10 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 10 * 60 * 60 * 1000).toISOString(),
  }
];

export const dummyAlerts: Alert[] = [
  {
    id: "al1",
    workspace_id: "Demo Brand",
    message: "Tín hiệu bùng nổ: Gần 5,000 bình luận tiêu cực xoay quanh chất lượng sản phẩm mới ra mắt.",
    severity: "critical",
    status: "new",
    signal_type: "mention_spike",
    affected_mentions_count: 4892,
    created_at: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
  },
  {
    id: "al2",
    workspace_id: "Demo Brand",
    message: "Khủng hoảng truyền thông: Bài bóc phốt trên trang cá nhân KOC @trangnguyen_review đạt 150k lượt xem, đề cập đến vấn đề an toàn thực phẩm.",
    severity: "critical",
    status: "acknowledged",
    signal_type: "high_reach",
    affected_mentions_count: 1250,
    created_at: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
  },
  {
    id: "al3",
    workspace_id: "Demo Brand",
    message: "Gia tăng đột biến đánh giá 1 sao (1-star reviews) trên nền tảng Google Maps tại chi nhánh Quận 1.",
    severity: "high",
    status: "new",
    signal_type: "mention_spike",
    affected_mentions_count: 85,
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "al4",
    workspace_id: "Demo Brand",
    message: "Từ khóa nhạy cảm 'tẩy chay' (boycott) được nhắc đến hơn 300 lần trong 24 giờ qua trên Threads.",
    severity: "high",
    status: "resolved",
    signal_type: "sensitive_topic",
    affected_mentions_count: 312,
    created_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "al5",
    workspace_id: "Demo Brand",
    message: "Khách hàng đe dọa khiếu nại lên Hội Bảo vệ Người tiêu dùng về chính sách hoàn trả mập mờ.",
    severity: "medium",
    status: "new",
    signal_type: "sensitive_topic",
    affected_mentions_count: 12,
    created_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
  }
];

export const dummyLeads: Lead[] = [
  {
    id: "l1",
    current_label: "lead_hot",
    labels: { sentiment: "neutral", topic: ["other"], relevance: true, urgency: "low", intent: "hot" },
    owner_id: "demo-user",
    owner_name: "Khách xem Demo",
    owner_email: "demo@example.com",
    assigned_at: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    workspace_id: "Demo Brand",
    platform: "facebook",
    post_id: "p1",
    author: "CEO Trần Quốc Khánh",
    content: "Chào bạn, bên mình đang cần triển khai hệ thống cho 500 nhân sự. Xin báo giá gói Enterprise và thời gian deploy dự kiến.",
    intent: "hot",
    intent_signals: ["báo giá", "enterprise", "500 nhân sự"],
    status: "new",
    phone: "0909 xxx 888",
    email: "khanh.tran@megacorp.vn",
    created_at: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    posted_at: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
  },
  {
    id: "l2",
    current_label: "lead_hot",
    labels: { sentiment: "neutral", topic: ["other"], relevance: true, urgency: "low", intent: "hot" },
    owner_id: "demo-lead-01",
    owner_name: "Nguyễn Minh Anh",
    owner_email: "minhanh.demo@insightflow.vn",
    assigned_at: new Date(Date.now() - 40 * 60 * 1000).toISOString(),
    contact_attempts: 1,
    last_contact_at: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
    workspace_id: "Demo Brand",
    platform: "tiktok",
    post_id: "p2",
    author: "Phạm Uyên Phương",
    content: "Shop ơi, đôi này còn size 38 màu trắng không? Mua 2 đôi có được freeship nội thành HN không ạ?",
    intent: "hot",
    intent_signals: ["còn size", "mua 2", "freeship"],
    status: "processing",
    phone: "0983 xxx 222",
    email: "phuong_uyen_99@company.com",
    created_at: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    posted_at: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
  },
  {
    id: "l3",
    current_label: "lead_hot",
    labels: { sentiment: "positive", topic: ["other"], relevance: true, urgency: "low", intent: "hot" },
    owner_id: "demo-user",
    owner_name: "Khách xem Demo",
    owner_email: "demo@example.com",
    assigned_at: new Date(Date.now() - 90 * 60 * 1000).toISOString(),
    workspace_id: "Demo Brand",
    platform: "news",
    post_id: "p3",
    author: "Lê Hoàng Phúc",
    content: "Mình muốn hợp tác mở đại lý phân phối độc quyền tại khu vực Miền Tây. Vui lòng gửi chính sách chiết khấu.",
    intent: "hot",
    intent_signals: ["hợp tác", "đại lý", "chiết khấu"],
    status: "new",
    phone: "0931 xxx 777",
    email: "phucle.business@gmail.com",
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    posted_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "l4",
    current_label: "lead_warm",
    labels: { sentiment: "neutral", topic: ["other"], relevance: true, urgency: "low", intent: "warm" },
    workspace_id: "Demo Brand",
    platform: "facebook",
    post_id: "p4",
    author: "Đinh Thị Thanh Tuyền",
    content: "Dịch vụ bên mình có xuất hóa đơn VAT không? Đang định ký hợp đồng năm.",
    intent: "warm",
    intent_signals: ["hóa đơn VAT", "ký hợp đồng"],
    status: "new",
    phone: "0912 xxx 345",
    email: "tuyendtt@vinagroup.com",
    created_at: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    posted_at: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "l5",
    current_label: "lead_warm",
    labels: { sentiment: "positive", topic: ["promotion"], relevance: true, urgency: "none", intent: "warm" },
    owner_id: "demo-user",
    owner_name: "Khách xem Demo",
    owner_email: "demo@example.com",
    closed_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    workspace_id: "Demo Brand",
    platform: "thread",
    post_id: "p5",
    author: "Nguyễn Tuấn Mạnh",
    content: "Thấy review khen nhiều quá, đang tính mua dùng thử mà giá hơi cao. Có mã giảm giá cho khách mới không shop?",
    intent: "warm",
    intent_signals: ["mua dùng thử", "mã giảm giá"],
    status: "completed",
    phone: "0868 xxx 999",
    email: "manh.nt@freelance.vn",
    created_at: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
    posted_at: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
  }
];

export const dummyLabelChangeRequests: LabelChangeRequest[] = [];


