import type { UserRoleProfile } from "@/lib/rbac";
import type { AlertData } from "@/stores/alert.store";
import type { Lead, Mention, Workspace } from "@/types/dashboard";

export const DEMO_PROFILE: UserRoleProfile = {
  uid: "demo-user-123",
  email: "demo@insightflow.vn",
  role: "brand_manager",
  companyDomain: "insightflow.vn",
  brandId: "highlandcoffee",
  brandName: "Highlands Coffee",
  displayName: "Khách hàng Trial",
  photoURL: "",
  permissions: [
    "dashboard",
    "mentions",
    "alerts",
    "leads",
    "reports",
    "staff_management",
    "brand_settings",
    "label_request_review",
    "response_settings",
  ],
  defaultRoute: "/demo",
  temporaryPasswordIssued: false,
};

export const DEMO_MOCK_ALERTS: AlertData[] = [
  {
    id: "demo-alert-001",
    source_id: "m-001",
    brand: "Highlands Coffee",
    source: "facebook",
    text: "CẢNH BÁO: Uống Phin Sữa Đá tại Highlands Coffee Lê Duẩn sáng nay bị ngộ độc thực phẩm nặng, đau bụng dữ dội và nôn mửa phải vào cấp cứu viện 115! Cần quản lý khu vực làm rõ nguồn gốc sữa tươi và đá viên!",
    sentiment: "negative",
    topic: "quality",
    severity: "critical",
    negativity_score: 96,
    created_at: new Date(Date.now() - 35 * 60 * 1000).toISOString(),
    status: "pending",
    collectionName: "annotations",
    url: "https://facebook.com/groups/reviewfoodsaigon/posts/998124",
    reach: 145000,
    likes: 540,
    comments: 230,
    shares: 110,
    author: "Nguyễn Minh Thư",
    social_profile_url: "https://facebook.com/minhthu.nguyen.review",
    content_type: "post",
    post_content: "CẢNH BÁO: Uống Phin Sữa Đá tại Highlands Coffee Lê Duẩn sáng nay bị ngộ độc thực phẩm nặng...",
  },
  {
    id: "demo-alert-002",
    source_id: "m-002",
    brand: "Highlands Coffee",
    source: "tiktok",
    text: "Nhân viên Highlands Nguyễn Trãi gắt gỏng với khách hàng, bắt chờ 35 phút không một lời giải thích. Quán làm ăn quá thiếu chuyên nghiệp!",
    sentiment: "negative",
    topic: "staff",
    severity: "high",
    negativity_score: 84,
    created_at: new Date(Date.now() - 1 * 24 * 3600 * 1000 - 4 * 3600 * 1000).toISOString(),
    status: "resolving",
    being_resolved_by: "Nguyen Van Crisis",
    being_resolved_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    collectionName: "annotations",
    url: "https://tiktok.com/@foodie_saigon/video/7291049201",
    reach: 98000,
    likes: 1240,
    comments: 310,
    shares: 145,
    author: "@foodie_saigon",
    content_type: "post",
  },
  {
    id: "demo-alert-003",
    source_id: "m-003",
    brand: "Highlands Coffee",
    source: "facebook",
    text: "Bát Bánh Mì xíu mại tại Highlands Coffee Lê Văn Sỹ phát hiện mẩu dị vật nhỏ. Khách đăng bài bức xúc trên nhóm Review Food Saigon với hơn 12.000 lượt tương tác.",
    sentiment: "negative",
    topic: "quality",
    severity: "critical",
    negativity_score: 92,
    created_at: new Date(Date.now() - 3 * 24 * 3600 * 1000 - 2 * 3600 * 1000).toISOString(),
    status: "pending",
    collectionName: "annotations",
    url: "https://facebook.com/groups/foodreviewers/posts/882190",
    reach: 112000,
    likes: 890,
    comments: 410,
    shares: 190,
    author: "Lê Văn Tùng",
    content_type: "post",
  },
  {
    id: "demo-alert-004",
    source_id: "m-004",
    brand: "Mixue",
    source: "threads",
    text: "Trà sữa nướng Mixue chi nhánh Cầu Giấy có mùi chua dịu của sữa thiu. Phản ảnh cho thu ngân thì chỉ nhận được thái độ thờ ơ.",
    sentiment: "negative",
    topic: "quality",
    severity: "high",
    negativity_score: 79,
    created_at: new Date(Date.now() - 5 * 24 * 3600 * 1000 - 3 * 3600 * 1000).toISOString(),
    status: "contact_waiting",
    customer_contact_opened_at: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    customer_contact_opened_by: "Tran Thi Lead",
    customer_contact_note: "Đã nhắn tin qua Threads đề nghị đổi sản phẩm mới và gửi voucher đền bù.",
    collectionName: "annotations",
    url: "https://threads.net/@ngoc_trai_2001/post/1092831",
    reach: 65000,
    likes: 210,
    comments: 89,
    shares: 34,
    author: "@ngoc_trai_2001",
    content_type: "post",
  },
  {
    id: "demo-alert-005",
    source_id: "m-005",
    brand: "Starbucks",
    source: "google_maps",
    text: "Giá cà phê tăng 15k/ly nhưng lượng nước lại ít hơn, đá chiếm 70% ly. Cảm thấy bị móc túi trắng trợn.",
    sentiment: "negative",
    topic: "price",
    severity: "medium",
    negativity_score: 68,
    created_at: new Date(Date.now() - 7 * 24 * 3600 * 1000 - 5 * 3600 * 1000).toISOString(),
    status: "pending",
    collectionName: "annotations",
    url: "https://maps.google.com/?cid=1092830192",
    reach: 42000,
    likes: 88,
    comments: 34,
    shares: 12,
    author: "Hoàng Anh Reviewer",
    content_type: "comment",
  },
  {
    id: "demo-alert-006",
    source_id: "m-006",
    brand: "Highlands Coffee",
    source: "facebook",
    text: "Ứng dụng đặt món Highlands bị lỗi thanh toán VNPAY tự động trừ tiền 2 lần nhưng không xuất đơn hàng. Nhiều khách hàng phản ánh trên nhóm CSKH.",
    sentiment: "negative",
    topic: "service",
    severity: "medium",
    negativity_score: 62,
    created_at: new Date(Date.now() - 10 * 24 * 3600 * 1000 - 1 * 3600 * 1000).toISOString(),
    status: "resolving",
    being_resolved_by: "Phạm Hải Đăng",
    being_resolved_at: new Date(Date.now() - 2 * 24 * 3600 * 1000).toISOString(),
    collectionName: "annotations",
    url: "https://facebook.com/groups/techsupport/posts/771239",
    reach: 28000,
    likes: 95,
    comments: 42,
    shares: 8,
    author: "Đỗ Thị Mai",
    content_type: "post",
  },
  {
    id: "demo-alert-007",
    source_id: "m-007",
    brand: "Highlands Coffee",
    source: "news",
    text: "Xác minh sự cố giao nhầm đơn hàng lớn tại Highlands Hàm Nghi: Quản lý chi nhánh đã liên hệ xin lỗi và hoàn trả 100% chi phí cho khách hàng.",
    sentiment: "negative",
    topic: "service",
    severity: "low",
    negativity_score: 45,
    created_at: new Date(Date.now() - 12 * 24 * 3600 * 1000 - 8 * 3600 * 1000).toISOString(),
    status: "resolved",
    resolved_at: new Date(Date.now() - 11 * 24 * 3600 * 1000).toISOString(),
    resolved_by_name: "Nguyen Van Crisis",
    resolved_by_email: "crisis@insightflow.vn",
    collectionName: "annotations",
    url: "https://tinfast247.vn/highlands-coffee-hoan-tien-khach-hang-2026",
    reach: 38000,
    likes: 120,
    comments: 25,
    shares: 10,
    author: "Báo Tin Tức F&B",
    content_type: "post",
  },
];

export const DEMO_MOCK_LEADS: Lead[] = [
  {
    id: "demo-lead-001",
    workspace_id: "highlandcoffee",
    platform: "facebook",
    author: "Nguyễn Thu Hà (HR Manager)",
    content: "Công ty mình tuần sau tổ chức hội thảo 150 người tại Q.1, cần đặt combo Cà Phê + Bánh Ngọt Highlands Coffee giao đúng 8h00 sáng. Đơn vị nào hoặc cửa hàng nào hỗ trợ làm hợp đồng & xuất hóa đơn VAT nhanh xin liên hệ gấp!",
    intent: "hot",
    intent_signals: ["Cần đặt combo cà phê", "Hội thảo 150 người", "Xuất hóa đơn VAT"],
    labels: { intent: "hot", relevance: true, sentiment: "positive", urgency: "normal" },
    status: "new",
    created_at: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    posted_at: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
    expiry_at: new Date(Date.now() + 4 * 3600 * 1000).toISOString(),
    url: "https://facebook.com/groups/hrcommunityvn/posts/882193",
    phone: "0908123456",
    email: "ha.nguyen@corpevent.vn",
    zalo_id: "0908123456",
    social_profile_url: "https://facebook.com/thuha.hr.manager",
  },
  {
    id: "demo-lead-002",
    workspace_id: "highlandcoffee",
    platform: "tiktok",
    author: "Trần Minh Đức",
    content: "Bên mình muốn mua 300 thẻ quà tặng E-Voucher Highlands 100k làm quà tặng sinh nhật nhân viên trong năm. Nhờ tư vấn phần trăm chiết khấu cho doanh nghiệp!",
    intent: "hot",
    intent_signals: ["Mua 300 E-Voucher", "Chiết khấu doanh nghiệp"],
    labels: { intent: "hot", relevance: true, sentiment: "positive", urgency: "normal" },
    status: "processing",
    owner_id: "demo-user-123",
    owner_name: "Tran Thi Lead",
    owner_email: "lead@insightflow.vn",
    assigned_at: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    claimed_at: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    posted_at: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    expiry_at: new Date(Date.now() + 6 * 3600 * 1000).toISOString(),
    url: "https://tiktok.com/@ductran_b2b/video/7891230491",
    phone: "0912345678",
    email: "duc.tran@techcorp.vn",
    zalo_id: "0912345678",
    messenger_id: "ductran.b2b",
  },
  {
    id: "demo-lead-003",
    workspace_id: "mixue",
    platform: "threads",
    author: "Phạm Hải Đăng",
    content: "Gia đình mình có mặt bằng góc 2 mặt tiền 90m2 tại KDC Chánh Nghĩa, Bình Dương. Đang muốn hợp tác nhượng quyền Mixue hoặc Highlands. Inbox tư vấn mặt bằng nhé!",
    intent: "warm",
    intent_signals: ["Mặt bằng 90m2 2 mặt tiền", "Nhượng quyền thương hiệu"],
    labels: { intent: "warm", relevance: true, sentiment: "positive", urgency: "normal" },
    status: "new",
    created_at: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
    posted_at: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
    expiry_at: new Date(Date.now() + 12 * 3600 * 1000).toISOString(),
    url: "https://threads.net/@haidang_property/post/901283",
    phone: "0989888999",
    email: "dang.pham@property.vn",
    zalo_id: "0989888999",
  },
  {
    id: "demo-lead-004",
    workspace_id: "starbucks",
    platform: "google_maps",
    author: "Lê Phương Thảo",
    content: "Công ty mình ở Landmark 81 muốn đăng ký dịch vụ giao cà phê cố định hàng ngày cho 40 nhân viên lúc 8h30 sáng. Admin shop liên hệ tư vấn giúp!",
    intent: "warm",
    intent_signals: ["Giao cà phê hàng ngày 40 ly", "Gói doanh nghiệp"],
    labels: { intent: "warm", relevance: true, sentiment: "positive", urgency: "normal" },
    status: "new",
    created_at: new Date(Date.now() - 6 * 3600 * 1000).toISOString(),
    posted_at: new Date(Date.now() - 6 * 3600 * 1000).toISOString(),
    expiry_at: new Date(Date.now() + 24 * 3600 * 1000).toISOString(),
    url: "https://maps.google.com/?cid=8812739182",
    phone: "0934567890",
    email: "thao.le@innovate.com.vn",
  },
  {
    id: "demo-lead-005",
    workspace_id: "highlandcoffee",
    platform: "facebook",
    author: "Vũ Hoàng Nam",
    content: "Highlands có bán hạt cà phê Roasted Culi đóng gói 1kg theo số lượng sỉ không shop? Mình lấy thử 20kg đợt đầu.",
    intent: "cold",
    intent_signals: ["Mua hạt cà phê sỉ 20kg"],
    labels: { intent: "cold", relevance: true, sentiment: "positive", urgency: "normal" },
    status: "completed",
    owner_id: "demo-user-123",
    owner_name: "Tran Thi Lead",
    closed_at: new Date(Date.now() - 1 * 3600 * 1000).toISOString(),
    created_at: new Date(Date.now() - 12 * 3600 * 1000).toISOString(),
    posted_at: new Date(Date.now() - 12 * 3600 * 1000).toISOString(),
    url: "https://facebook.com/namvu.coffee/posts/1029381",
    phone: "0977112233",
    result_type: "converted",
    result_recorded_at: new Date(Date.now() - 1 * 3600 * 1000).toISOString(),
  },
];

export const DEMO_MOCK_WORKSPACES: Workspace[] = [
  { id: "highlandcoffee", name: "Highlands Coffee", brand_name: "Highlands Coffee", created_at: new Date().toISOString() },
  { id: "starbucks", name: "Starbucks Vietnam", brand_name: "Starbucks", created_at: new Date().toISOString() },
  { id: "mixue", name: "Mixue Vietnam", brand_name: "Mixue", created_at: new Date().toISOString() },
  { id: "phuclong", name: "Phúc Long Tea & Coffee", brand_name: "Phúc Long", created_at: new Date().toISOString() },
];

export const DEMO_MOCK_MENTIONS: Mention[] = [
  {
    id: "demo-m-001",
    workspace_id: "highlandcoffee",
    platform: "facebook",
    author: "Nguyễn Hải Đăng",
    content: "Không gian Highlands Coffee cơ sở Hàm Nghi mới decor lại đẹp và thoáng quá! Nhân viên tươi cười thân thiện, trà sen vàng vị thanh vừa phải 5 sao!",
    sentiment: "positive",
    topic: "experience",
    posted_at: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    created_at: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    reach: 12500,
    likes: 420,
    comments: 85,
    shares: 24,
    url: "https://facebook.com/posts/demo-m-001",
  },
  {
    id: "demo-m-002",
    workspace_id: "highlandcoffee",
    platform: "tiktok",
    author: "@coffeelover_saigon",
    content: "Review thử Phin Sữa Đá Highlands buổi sáng: Đậm đà chuẩn gu người Việt, nạp năng lượng chạy deadline đỉnh của chóp!",
    sentiment: "positive",
    topic: "quality",
    posted_at: new Date(Date.now() - 5 * 3600 * 1000).toISOString(),
    created_at: new Date(Date.now() - 5 * 3600 * 1000).toISOString(),
    reach: 85000,
    likes: 3400,
    comments: 290,
    shares: 180,
    url: "https://tiktok.com/@coffeelover_saigon/video/demo-002",
  },
  {
    id: "demo-m-003",
    workspace_id: "highlandcoffee",
    platform: "threads",
    author: "@thanhthao_99",
    content: "Combo 49k gồm Cà phê Phin + Bánh Mì Que của Highlands siêu hời cho dân văn phòng ăn sáng nhanh gọn.",
    sentiment: "positive",
    topic: "price",
    posted_at: new Date(Date.now() - 10 * 3600 * 1000).toISOString(),
    created_at: new Date(Date.now() - 10 * 3600 * 1000).toISOString(),
    reach: 18400,
    likes: 620,
    comments: 110,
    shares: 45,
    url: "https://threads.net/@thanhthao_99/post/demo-003",
  },
  {
    id: "demo-m-004",
    workspace_id: "highlandcoffee",
    platform: "google_maps",
    author: "Lê Hoàng Phúc",
    content: "Wifi ở chi nhánh Nguyễn Du khá chập chờn giờ cao điểm, nhưng bù lại bảo vệ dắt xe siêu nhiệt tình và chu đáo.",
    sentiment: "neutral",
    topic: "service",
    posted_at: new Date(Date.now() - 18 * 3600 * 1000).toISOString(),
    created_at: new Date(Date.now() - 18 * 3600 * 1000).toISOString(),
    reach: 4500,
    likes: 38,
    comments: 12,
    shares: 2,
    url: "https://maps.google.com/?cid=demo-004",
  },
  {
    id: "demo-m-005",
    workspace_id: "highlandcoffee",
    platform: "facebook",
    author: "Trần Bảo Ngọc",
    content: "Freeze Trà Xanh Highlands vị matcha ngậy vừa béo, kem tươi mịn màng không bị gắt cổ. Món khoái khẩu nhất mỗi khi đi họp nhóm!",
    sentiment: "positive",
    topic: "quality",
    posted_at: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
    created_at: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
    reach: 22000,
    likes: 890,
    comments: 145,
    shares: 67,
    url: "https://facebook.com/posts/demo-m-005",
  },
  {
    id: "demo-m-006",
    workspace_id: "highlandcoffee",
    platform: "befood",
    author: "Đỗ Anh Tuấn",
    content: "Đơn hàng BeFood giao cực nhanh trong 15 phút, đá chưa kịp tan, ly đậy nắp chắc chắn không rỉ một giọt nào ra ngoài.",
    sentiment: "positive",
    topic: "delivery",
    posted_at: new Date(Date.now() - 36 * 3600 * 1000).toISOString(),
    created_at: new Date(Date.now() - 36 * 3600 * 1000).toISOString(),
    reach: 9800,
    likes: 210,
    comments: 34,
    shares: 12,
  },
  {
    id: "demo-m-007",
    workspace_id: "starbucks",
    platform: "tiktok",
    author: "@starbucks_fan_vn",
    content: "Bắt trend món mới Matcha Coconut Cloud mượt như mây của Starbucks, thơm dịu hương dừa nướng mát lạnh!",
    sentiment: "positive",
    topic: "marketing",
    posted_at: new Date(Date.now() - 2 * 24 * 3600 * 1000).toISOString(),
    created_at: new Date(Date.now() - 2 * 24 * 3600 * 1000).toISOString(),
    reach: 120000,
    likes: 5600,
    comments: 420,
    shares: 310,
  },
  {
    id: "demo-m-008",
    workspace_id: "mixue",
    platform: "threads",
    author: "@haikid_02",
    content: "Kem Mixue 10k ngon vô địch tầm giá, học sinh sinh viên giải nhiệt ngày nắng nóng đúng đỉnh!",
    sentiment: "positive",
    topic: "price",
    posted_at: new Date(Date.now() - 3 * 24 * 3600 * 1000).toISOString(),
    created_at: new Date(Date.now() - 3 * 24 * 3600 * 1000).toISOString(),
    reach: 45000,
    likes: 1890,
    comments: 230,
    shares: 98,
  },
  {
    id: "demo-m-009",
    workspace_id: "highlandcoffee",
    platform: "youtube",
    author: "Vinh Vlog F&B",
    content: "Trải nghiệm làm việc 8 tiếng tại Highlands Coffee Landmark: Ổ cắm điện phủ khắp bàn, không gian yên tĩnh sáng tạo.",
    sentiment: "positive",
    topic: "experience",
    posted_at: new Date(Date.now() - 4 * 24 * 3600 * 1000).toISOString(),
    created_at: new Date(Date.now() - 4 * 24 * 3600 * 1000).toISOString(),
    reach: 95000,
    likes: 4100,
    comments: 520,
    shares: 210,
  },
  {
    id: "demo-m-010",
    workspace_id: "phuclong",
    platform: "facebook",
    author: "Phương Anh Review",
    content: "Trà Đào Cam Sả Phúc Long vị trà đậm đà đặc trưng không lẫn đi đâu được, miếng đào giòn ngọt sần sật.",
    sentiment: "positive",
    topic: "quality",
    posted_at: new Date(Date.now() - 5 * 24 * 3600 * 1000).toISOString(),
    created_at: new Date(Date.now() - 5 * 24 * 3600 * 1000).toISOString(),
    reach: 34000,
    likes: 1450,
    comments: 198,
    shares: 88,
  },
];
